### ISSUE TITLE
LTC deletes all thumbnails

### ISSUE THREAD

**Issue by romano** [wereii/lemmy-thumbnail-cleaner#4]
Lemmy Thumbnail Cleaner seems to delete all thumbnails. Environment variables were set to default (3 months, 300 interval, 300 query limit, no delete_on_not_found). Pictrs version 0.5.15, Lemmy version 0.19.4, Postgres version 16-alpine3.20

Attached screenshot (new thumbnails were generated after disabling LTC):
![ltc_bug](https://github.com/wereii/lemmy-thumbnail-cleaner/assets/92785/a016e88c-9e7d-472b-b849-9accc40de122)

**Comment by wereii** [comment]
That should not happen, though without logs from the container I can't see how/what could go wrong.  
The important bit, is that LTC (funny abbreviation:) ) outputs how many thumbnails can be cleaned at the start:

`[2024-06-10T17:47:05Z INFO  lemmy_thumbnail_cleaner] Database contains 76 of thumbnails that can be cleaned up`

 if the number is huge (which depends on the instance traffic) then that would mean some kind of issue with the month filter but that that part is handled by postgres.
